---
title: "Visualizacion imagen 2"
author: "Ricardo Morales"
date: "2023-03-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Imagen 2
#Ejer 2

library("ggplot2")
library("dplyr")
library("ggpubr")
library("ggrepel")

ruta <- "https://raw.githubusercontent.com/martintinch0/CienciaDeDatosParaCuriosos/master/data/gapminder.csv"
df_gapminder <- read.table(file = ruta, sep=';', header = TRUE, 
                           stringsAsFactors = FALSE)
figure1 <- df_gapminder %>% 
  filter (between(year, 2007, 2007)) %>%
  ggplot(aes(x = gdpPercap, y = lifeExp, 
             size=pop, color=continent)) +
  geom_point() + 
  geom_text_repel(aes(label=country), size = 1.5) +
  labs(x = "Ingreso promedio (USD)",
       y = "Expectativa de vida al nacer (años)",
       title="Esperanza de vida debido al ingreso promedio - 2007",
       caption="Fuente: Gapminder",
       color="Continente: ") +
  guides(size=FALSE) + 
  theme(legend.position="bottom", 
        legend.title = element_text(face = "bold", color = "black", size= 10), 
        panel.background = element_rect(fill = "white", colour = "grey80"), 
        panel.grid.major = element_line(colour = "grey90", linetype = "dotted"))

figure2 <- df_gapminder %>% 
  filter (between(year, 2007, 2007)) %>%
  ggplot(aes(x = gdpPercap, y = lifeExp, 
             size=pop, color=continent)) +
  geom_point() + 
  geom_text_repel(aes(label=country), size = 1.5) +
  scale_x_continuous(limits = c(6000, 8000)) +
  scale_y_continuous(limits = c(65, 80)) +
  guides(size=FALSE) + 
  theme(legend.position = "none",
        axis.title = element_blank(),
        legend.title = element_text(face = "bold", color = "black", size= 10), 
        panel.background = element_rect(fill = "white", colour = "grey80"), 
        panel.grid.major = element_line(colour = "grey90", linetype = "dotted"))

figure1 + annotation_custom(ggplotGrob(figure2), 
                                 xmin = 30000, xmax = 50000, 
                                 ymin = 40, ymax = 60
```


